Update PBL documents
Xilinx/xup_aie_training pull request #21
Opened 2023-12-04 10:39 UTC by vickyiii

1. Update the readme
2. add the x86simulation in Makefile
3. Change the fir single kernel code to drop the first output

2023-12-04 11:38 UTC, mariodruiz requested changes

2023-12-04 15:29 UTC, vickyiii commented on docs/fir_single_kernel.md
> +| ---- | ----------------------------------------------------------------------- | -------------------------------------------------------------------------------------------- |
Fixed

2023-12-04 15:29 UTC, vickyiii commented on docs/fir_single_kernel.md
> +| 1    | [Software Implementation](./notebook/fir_lowpass1.ipynb)                   | Generate the Complex Signal Data with High-frequency Noise                                   |
Done

2023-12-04 15:38 UTC, mariodruiz commented on docs/fir_single_kernel.md
> +| ---- | ----------------------------------------------------------------------- | -------------------------------------------------------------------------------------------- |
I don't see the changes

2023-12-04 15:49 UTC, vickyiii commented on pbl/aie_single_kernel/fir_lowpass/aie/Makefile
>  x86sim:
I prefer to set the aieemu and x86sim as two independent rules. To make the above change requires a big update on the tutorial.
https://github.com/Xilinx/Vitis-Tutorials/blob/714ef8d4a0b3ba1cc4d7ed993e1fe5ed5c4cd9c5/AI_Engine_Development/AIE/Feature_Tutorials/08-dsp-library/part_2/Makefile#L36

2023-12-05 09:09 UTC, mariodruiz commented on docs/fir_single_kernel.md
> +```
```suggestion
    ```
```

2023-12-05 09:11 UTC, mariodruiz approved these changes

2023-12-05 09:11 UTC, merged